CREATE TABLE "job_posting" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_title_short" varchar NOT NULL,
  "job_title" varchar NOT NULL,
  "job_location" varchar,
  "job_via" varchar,
  "job_schedule_type" varchar,
  "job_work_from_home" boolean NOT NULL,
  "search_location" varchar NOT NULL,
  "job_posted_date" date NOT NULL,
  "job_no_degree_mention" boolean NOT NULL,
  "job_health_insurance" boolean NOT NULL,
  "job_country" varchar,
  "salary_rate" varchar,
  "salary_year_avg" int,
  "salary_hour_avg" int,
  "company_name" varchar NOT NULL,
  "job_skills" varchar[],
  "job_type_skills" jsonb
);

CREATE TABLE "job_posts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title_short_id" bigint NOT NULL,
    "company_name_id" bigint,
    "via_id" bigint,
    "schedule_type_id" bigint,
    "location_id" bigint,
    "title" varchar NOT NULL,
    "search_location" varchar NOT NULL,
    "work_from_home" boolean NOT NULL,
    "posted_date" date NOT NULL,
    "no_degree_mention" boolean NOT NULL,
    "health_insurance" boolean NOT NULL,
    "salary_rate" varchar,
    "salary_year_avg" float,
    "salary_hour_avg" float
);

CREATE TABLE "companies" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "locations" (
    "id" bigint PRIMARY KEY,
    "country_id" bigint NOT NULL,
    "name" varchar NOT NULL
);

CREATE TABLE "countries" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "skills" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "short_titles" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "vias" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "schedule_types" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "types" (
    "id" bigint PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE "job_skills" (
    "job_id" bigint NOT NULL,
    "skill_types_id" bigint NOT NULL,
    PRIMARY KEY ("job_id", "skill_types_id")
);

CREATE TABLE "skill_types" (
    "id" bigint NOT NULL,
    "skill_id" bigint NOT NULL,
    "type_id" bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX ON "skill_types" ("skill_id", "type_id");

COMMENT ON
TABLE "job_posting" IS 'Tabla original / staging del dataset sin normalizar';

ALTER TABLE "job_posts"
ADD FOREIGN KEY ("title_short_id") REFERENCES "short_titles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_posts"
ADD FOREIGN KEY ("company_name_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_posts"
ADD FOREIGN KEY ("via_id") REFERENCES "vias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_posts"
ADD FOREIGN KEY ("schedule_type_id") REFERENCES "schedule_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_posts"
ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "locations"
ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_skills"
ADD FOREIGN KEY ("job_id") REFERENCES "job_posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_skills"
ADD FOREIGN KEY ("skill_types_id") REFERENCES "skill_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_types"
ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_types"
ADD FOREIGN KEY ("type_id") REFERENCES "types" ("id") DEFERRABLE INITIALLY IMMEDIATE;